### ISSUE TITLE
Failed to load the js-hyperclick package

### ISSUE THREAD

**Issue by capaj** [AsaAyers/js-hyperclick#1]
Just got this after installing.

**Atom Version**: 1.0.19
**System**: Debian GNU/Linux
**Thrown From**: [js-hyperclick](https://github.com/AsaAyers/js-hyperclick) package, v1.1.1

### Stack Trace

Failed to load the js-hyperclick package

```
At Cannot find module 'resolve'

Error: Cannot find module 'resolve'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/capaj/.atom/packages/js-hyperclick/lib/suggestions.js:21:16)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/capaj/.atom/packages/js-hyperclick/lib/js-hyperclick.js:9:22)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at /usr/share/atom/resources/app.asar/src/package.js:192:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:485:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -1:26.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.3.0
autocomplete-paths, v1.0.2
coffee-links, v0.1.0
git-log, v0.4.1
hyperclick, v0.0.32
js-hyperclick, v1.1.1
language-cjsx, v0.3.0
language-diff, v0.3.1
language-dotenv, v1.0.0
language-gitignore, v0.2.0
language-nginx, v0.6.1
language-soy, v0.3.0
linter, v1.9.0
linter-js-standard, v3.2.1
local-history, v3.2.3
open-recent, v2.3.0
react, v0.12.10
standard-formatter, v1.1.3

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
Sorry, I see my mistake. v1.1.2 should fix it

**Comment by AsaAyers** [comment]
https://github.com/AsaAyers/js-hyperclick/commit/faf980fb1cce95cbebbcec9a9b7ec2132cee72b5 for anyone interested

**Comment by capaj** [comment]
that was incredibly fast, thanks @AsaAyers

**Comment by AsaAyers** [comment]
Today I started showing notifications in `code-links` prompting people to move here. I'm standing by because these kinds of little mistakes are easy to make and fix, but are extremely frustrating for users.

**Comment by jt3k** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14


### Stack Trace

Failed to activate the file-icons package

```
At Error parsing /Users/a.gurtovoy/.atom/packages/file-icons/node_modules/unset-value/node_modules/has-value/package.json: Unexpected end of JSON input

SyntaxError: Error parsing /Users/a.gurtovoy/.atom/packages/file-icons/node_modules/unset-value/node_modules/has-value/package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:183:20)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/unset-value/index.js:11:11)
    at /packages/file-icons/node_modules/unset-value/index.js:34:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/cache-base/index.js:8:11)
    at /packages/file-icons/node_modules/cache-base/index.js:263:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/base/index.js:5:17)
    at /packages/file-icons/node_modules/base/index.js:437:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
aesthetic-ui 4.0.0 
atom-ide-ui 0.6.0 
atom-like-brackets-editor 1.2.0 
atom-material-ui 2.0.6 
atom-monokai 0.10.9 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
blame 1.0.1 
busy-signal 1.4.3 
color-tabs 0.1.8 
colorful-json 1.1.0 
comment 0.6.1 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.14 
filecolor 0.4.0 
fold-functions 0.5.0 
fold-lines 0.2.2 
git-blame 1.3.1 
git-control 0.9.0 
git-plus undefined 
git-status 0.3.4 
git-time-machine 1.5.9 
guess-indent 0.1.0 
highlight-bad-chars 1.0.7 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-typescript 0.6.1 
indent-detective 0.1.1 
indent-guide-improved 1.4.13 
indent-toggle-on-paste 0.1.3 
indent-tooltip 0.3.1 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-dot-template 0.2.0 
language-javascript-jsx 0.3.7 
language-mjml 1.10.0 
language-plantuml 0.2.0 
language-postcss 1.3.1 
language-pug 0.0.21 
language-twig 1.6.3 
language-volt 0.2.2 
lines 0.13.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
linter-xo 0.23.1 
markdown-folder 0.5.0 
markdown-scroll-sync 2.1.2 
monokai 0.24.0 
monokai-seti 0.9.0 
motepair 0.24.0 
npm-install 4.0.4 
npm-plus 0.4.0 
pigments 0.40.2 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.7.0 
prettier-atom 0.43.0 
project-manager 3.3.5 
prompt-big-file 0.4.0 
react 0.17.0 
react-snippets 1.0.1 
remember-folds 0.3.0 
semanticolor 3.5.5 
set-syntax 0.4.0 
seti-ui 1.9.0 
simple-drag-drop-text 0.3.6 
styles-highlighter 2.4.0 
Stylus 3.1.1 
stylus-autocompile 0.6.1 
sublime-block-comment 0.5.1 
svg-preview 0.12.1 
sync-settings 0.8.3 
tool-bar-markdown-writer 0.3.0 
trailing-spaces 0.4.0 
turbo-javascript 1.4.0 
umd-snippets 0.1.1 
```

same problem

**Comment by AsaAyers** [comment]
> Thrown From: file-icons package 2.1.14

Try uninstalling and reinstalling that package.
