### ISSUE TITLE
not working with hyperclick v0.0.35 

### ISSUE THREAD

**Issue by capaj** [AsaAyers/js-hyperclick#11]
maybe it is just me. I do get 
```
Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/home/capaj/.atom/packages/hyperclick/lib/main.js:32:13)
    at Provider.module.exports.Provider.provide (/usr/share/atom-beta/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom-beta/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
thrown on startup.

**Comment by AsaAyers** [comment]
That's because even though Atom provides a mechanism to version an API, Hyperclick just uses `0.0.0` and breaks the API without warning whenever they want.

**Comment by AsaAyers** [comment]
I just pushed 1.4.1, which should fix this. #10 said it fixed it and I merged. Please let me know of Hyperclick broke anything else

**Comment by capaj** [comment]
@AsaAyers wow, you are fast. Yeah, 1.4.1 works flawlessly, closing this

**Comment by AsaAyers** [comment]
I just pushed the merge button, but you're welcome :smile_cat:
