### ISSUE TITLE
Error on start up.

### ISSUE THREAD

**Issue by ctrlplusb** [AsaAyers/js-hyperclick#33]
I think it started happening after upgrading to Atom `1.10.0`

> Failed to activate the js-hyperclick package

```
SyntaxError: Error parsing /Users/sean/.atom/packages/js-hyperclick/node_modules/ast-types/package.json: Unexpected token }
    at Object.parse (native)
    at readPackage (module.js:95:52)
    at tryPackage (module.js:105:13)
    at Function.Module._findPath (module.js:167:20)
    at Module._resolveFilename (module.js:337:25)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/sean/.atom/packages/js-hyperclick/node_modules/recast/lib/types.js:5:18)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/sean/.atom/packages/js-hyperclick/node_modules/recast/main.js:1:92)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/sean/.atom/packages/js-hyperclick/node_modules/regenerator/lib/visit.js:13:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/sean/.atom/packages/js-hyperclick/node_modules/regenerator/main.js:15:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/sean/.atom/packages/js-hyperclick/node_modules/babel-core/lib/transformation/transformers/other/regenerator.js:12:20)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
The error was thrown from the js-hyperclick package. You can help by creating an issue. Please explain what actions triggered this error.
```

**Comment by AsaAyers** [comment]
Try uninstalling and reinstalling `js-hyperclick`. The syntax error is in the `ast-types` package that I have no control over.

I think apm (npm?) just wrote the file wrong or it got corrupted. I just installed that package and verified that the `package.json` is valid (I also don't think it's possible to publish a bad `package.json`)

**Comment by ctrlplusb** [comment]
Thanks for the quick response!
