### ISSUE TITLE
Uncaught Error: Cannot find module 'atom' from '/Users/miguel/.atom/packages/js-hyperclick/lib'

### ISSUE THREAD

**Issue by lezama** [AsaAyers/js-hyperclick#6]
You can reproduce this error by trying to use js-hyperlink on `Range` in https://github.com/AsaAyers/js-hyperclick/blob/master/lib/suggestions.js#L8

Thanks for working on this really useful package!

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [js-hyperclick](https://github.com/AsaAyers/js-hyperclick) package, v1.2.0

### Stack Trace

Uncaught Error: Cannot find module 'atom' from '/Users/miguel/.atom/packages/js-hyperclick/lib'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/resolve/lib/sync.js:33

Error: Cannot find module 'atom' from '/Users/miguel/.atom/packages/js-hyperclick/lib'
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/resolve/lib/sync.js:33:11)
  at resolveModule (/Users/miguel/.atom/packages/js-hyperclick/lib/suggestions.js:36:38)
  at Object.callback (/Users/miguel/.atom/packages/js-hyperclick/lib/suggestions.js:85:28)
  at HyperclickForTextEditor._confirmSuggestion (/Users/miguel/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:72:20)
  at HyperclickForTextEditor._onMouseDown (/Users/miguel/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:127:14)

```

### Commands

```
 63x -6:44.1.0 core:undo (atom-text-editor.editor.is-focused)
     -6:33.5.0 core:save (atom-text-editor.editor.is-focused)
     -6:27.8.0 core:close (atom-text-editor.editor.is-focused)
     -6:13.6.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -6:11.3.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -4:12.6.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
  2x -4:01.7.0 core:close (atom-text-editor.editor.is-focused)
     -3:52.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:48.4.0 core:close (atom-text-editor.editor.is-focused)
     -3:40.4.0 core:redo (atom-text-editor.editor.is-focused)
     -3:39.1.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -3:36.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:36.3.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
  2x -3:33.8.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:24.9.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "atom-jsfmt"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-log, v0.4.1
hyperclick, v0.0.32
js-hyperclick, v1.2.0
linter, v1.9.1
linter-eslint, v3.1.1
minimap, v4.15.0
react, v0.12.10
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
Thanks. I hadn't noticed this. I'll address it in 2 parts:

1. it shouldn't throw when it can't find a module
2. Because `atom` isn't really in `node_modules` and can't be found with the normal resolution algorithm, I don't know what this should do.
