### ISSUE TITLE
Failed to activate the js-hyperclick package

### ISSUE THREAD

**Issue by plusOneSecond** [AsaAyers/js-hyperclick#80]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12
**Thrown From**: [js-hyperclick](https://github.com/AsaAyers/js-hyperclick) package 1.11.0

### Stack Trace

Failed to activate the js-hyperclick package

```
At Package not initialized

Error: Package not initialized
    at /packages/hyperclick/index.js:1:152957)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:377:25
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
  2x -7:51 core:move-up (input.hidden-input)
  2x -7:49.5.0 pane:show-next-item (input.hidden-input)
  2x -6:18.9.0 editor:consolidate-selections (input.hidden-input)
     -6:02.0 core:cancel (input.hidden-input)
     -4:44.4.0 core:backspace (input.hidden-input)
     -4:42.6.0 core:confirm (input.hidden-input)
     -4:38.9.0 core:select-all (input.hidden-input)
     -4:38.7.0 core:cut (input.hidden-input)
     -4:33.8.0 core:select-all (input.hidden-input)
  2x -4:30.5.0 core:confirm (input.hidden-input)
  4x -3:04.5.0 core:backspace (input.hidden-input)
     -3:01.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
hyperclick 0.1.3 
js-hyperclick 1.11.0 
monokai 0.24.0 
```

**Comment by AsaAyers** [comment]
Please let me know if this is still happening and I can try to look into it.
